### ISSUE TITLE
Ubuntu 16.10 & 16.04 - Unable to drag and drop stencil to document

### ISSUE THREAD

**Issue by caiofior** [prikhi/pencil#856]
I'm unable to drag and drop stencil to document in version 2.0.12 and 2.0.5 in ubuntu 16.04 & 16.10.

I installed the software with deb package

On windows it works like a charm and a can see the changes made on windows environment.

**Comment by JohannesAhlers** [comment]
Xubuntu 16.10 is affected by this, too.
Is there any other way than drag an drop to get the elements to the document?

**Comment by BramVanBerkel** [comment]
Yup, same problem here on Ubuntu gnome 16.04

**Comment by Makreig** [comment]
I also have this issue, currently using Linux Mint 17

**Comment by caiofior** [comment]
I tried again and again ad found the culprit and the solution.

This version of the software is a firefox app and in latest version of the browser drag and drop is no more supported.

So I compiled the software from source and enclosed firefox 40.03; now it works like a charm.

This is the result, unzip and exec the script pencil-2.0.21/pencil.sh

https://mega.nz/#!ColgHSrb!5WwnGZanWW6e6iiWCUQokpmzxxsKqTzJBhZ4n8HxGJY

Tested on Ubuntu 16.10

**Comment by prikhi** [comment]
I think this is fixed by modifying our deb to include xulrunner instead of depending on firefox

**Comment by flo1o1** [comment]
I still have this issue with pencil-prototyping 2.0.21 (.deb from GitHub). I'm using Kubuntu (KDE) 16.04
```
~ » dpkg -I Downloads/pencil-prototyping-2.0.21-ubuntu-all.deb
 neues Debian-Paket, Version 2.0.
 Größe 23563114 Byte: control-Archiv= 433 Byte.
     385 Byte,    12 Zeilen      control              
 Package: pencil-prototyping
 Replaces: evoluspencil (<< 2.0-6~)
 Breaks: evoluspencil (<< 2.0-6~)
 Version: 2.0.21
 Section: devel
 Priority: optional
 Architecture: all
 Depends: firefox (>= 4.0) | iceweasel (>= 4.0)
 Installed-Size: 9216
 Maintainer: Pavan Rikhi <pavan.rikhi@gmail.com>
 Description: GUI Prototyping/Wireframing
  Pencil is a multiplatform tool for GUI Prototyping/Wireframing
```

I have Mozilla Firefox 50.1.0 installed.

Installing [Pencil 3 RC1](https://github.com/evolus/pencil/releases) fixes the issue for me.

**Comment by prikhi** [comment]
This hasn't been fixed. Don't know when I will have the time to fix it.

Someone else could start by taking a look at the `ubuntu` function in `builds/build.sh`. The fix would include xulrunner in the package and modify the `pencil` script to call that xulrunner instead of firefox/iceweasel, then remove firefox/iceweasel from the ubuntu dependencies.

**Comment by ferulisses** [comment]
Pencil 3 RC2 works for me, Ubuntu 16.04 LTS: https://github.com/evolus/pencil/releases

**Comment by ccmksy** [comment]
I think the problem is Java. 
I have two computer, both also installed Pencil 2.0.5, but one installed with Java7.0, another one installed with Java8.0.....I discover that I can use the Pencil under Java7.0, but cannot use under Java 8.0.
